name: Generate Static Site

on:
  push:
    branches:
      - main  # Or whichever branch you are using

jobs:
  generate-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # Python 3.12.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Flask

      - name: Run the script to generate static site
        run: |
          python app.py  # generate the static site

      
      - name: Commit and push generated static files
        run: |
          git config --global user.name "emmaenglishwilkins"
          git config --global user.email "emmawilkins@penguincodingschool.com"
          git add static_site/
          git diff --cached --quiet || (git commit -m "Regenerate static site" && git pull --rebase && git push origin main)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

